### ISSUE TITLE
Upload图片出错

### ISSUE THREAD

**Issue by ghtHack** [visual-openllm/visual-openllm#11]
======>Auto Resize Image...
Resize image form 1176x253 to 512x128
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\gradio\blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\Anaconda3\envs\imufe_gpt\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\admin\Desktop\imufe_gpt\visual-openllm\visual_openllm\visual_openllm.py", line 1326, in run_image
    description = self.models["ImageCaptioning"].inference(image_filename)
KeyError: 'ImageCaptioning'

**Comment by ghtHack** [comment]
补充一下：图片能正常上传到image文件夹

**Comment by PeterDing** [comment]
`ImageCaptioning` 默认不加载。
目前，鉴于ChatGLM-6B的模型能力，我们只支持 对话和文生图 两个模型。
之后我们会尝试把更多图像模型的功能加入。

**Comment by ghtHack** [comment]
谢谢回答！

**Comment by greasebig** [comment]
> `ImageCaptioning` 默认不加载。 目前，鉴于ChatGLM-6B的模型能力，我们只支持 对话和文生图 两个模型。 之后我们会尝试把更多图像模型的功能加入。

对话模型是什么意思？image caption和vqa现在支持了吗？能不能对图片提多个问题并一次性回答？

**Comment by PeterDing** [comment]
多步骤的提问目前还不行，我们调试模型。

**Comment by xbsdsongnan** [comment]
显存８Ｇ是否可以支持
