### ISSUE TITLE
图片加载故障

### ISSUE THREAD

**Issue by abelxiaoxing** [visual-openllm/visual-openllm#14]
系统：win10的wsl2——ubuntu22.04
显卡：tesla p40
在pip install -r 装好环境后，无法正常运行，排查后发现是transformers的安装版本过高导致，因此删除llm.py文件第46行的“device_map="auto"“这部分内容，顺利启动。

文字表现正常但加载图片后出现以下报错，能帮忙分析一下问题原因吗？

======>Auto Resize Image...
Resize image form 3840x2160 to 512x256
Traceback (most recent call last):
  File "/home/abel/anaconda3/lib/python3.9/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/abel/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/home/abel/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/abel/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/abel/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker
_thread
    return await future
  File "/home/abel/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/abel/visual-openllm/visual_openllm/visual_openllm.py", line 1326, in run_image
    description = self.models["ImageCaptioning"].inference(image_filename)
KeyError: 'ImageCaptioning'

**Comment by PeterDing** [comment]
见 #11
